name: build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: build the project and run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: install packages
        run: sudo apt-get update && sudo apt-get install --yes cmake g++
      - name: configure
        run: mkdir --parents build && cd build && cmake ..
      - name: build
        run: cd build && make --jobs=16
      - name: test
        run: cd build && make test
